import type { Metadata } from "next"
import "./globals.css"
import { Kanit } from "next/font/google"
import { UserContextProvider } from "@/contexts/useUserContext"
import { LayoutContextProvider } from "@/contexts/useLayoutContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
const kanit = Kanit({
  subsets: ["thai"],
  display: "fallback",
  weight: "300",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={kanit.className}>
        <UserContextProvider>
          <LayoutContextProvider>{children}</LayoutContextProvider>
        </UserContextProvider>
      </body>
    </html>
  )
}
